### ISSUE TITLE
Ability to recreate IOS/Android folders

### ISSUE THREAD

**Issue by wtrocki** [react-native-community/cli#1070]
## Describe the Feature

When creating react-native projects IOS and Android folders are created with native code. Since auto-linking is now enabled in situations where there will be no changes in this native codebase is there any justification to commit them to the repository?

Would it be possible to dynamically recreate IOS and Android folders with content without calling init and copying pasting code?

**Comment by wtrocki** [comment]
I found solution: 

```
react-native init --folder ios@0.60.1
```

Closing as this is not an issue

**Comment by wtrocki** [comment]
Typical approach with using `react-native upgrade` is not regenerating the ios and android folders.

**Comment by thymikee** [comment]
> is there any justification to commit them to the repository?

Yes, otherwise you wouldn't easily be able to run projects from native IDEs, since these would live in node_modules and could get erased any time. 

> Would it be possible to dynamically recreate IOS and Android folders with content without calling init and copying pasting code?

This is a question that comes back once in a while, e.g. here: #503. I don't really see such command being less of a hack than `init` and replacing. It's a very rare use-case. 

I'm open to a discussion on how we could simplify handling native projects, but I believe https://github.com/react-native-community/discussions-and-proposals is a better place to do so.

**Comment by thymikee** [comment]
> Typical approach with using react-native upgrade is not regenerating the ios and android folders

Why would it? It's not advertised to do so.

**Comment by wtrocki** [comment]
> This is a question that comes back once in a while, e.g. here: #503. I don't really see such command being less of a hack than init and replacing. It's a very rare use-case.

Ok. This is great clarification and fully aware that this is the rare use case. 
Thank you for comming back so fast with explanation! Closing as we both agreed that there is nothing to action here.
