### ISSUE TITLE
Remove bash dependency in setup_env.sh by using sh instead

### ISSUE THREAD

**Issue by emanuelb** [react-native-community/cli#1090]
## Description

The file setup_env.sh is using `bash` which can be avoided by using `/bin/sh` instead (always available on linux), building of react-native app on alpine linux (in docker container) without bash will work after applying the change.
https://github.com/react-native-community/cli/blob/15f5c7b85af6d299616756d84b5348f371b812ff/packages/cli/setup_env.sh#L1

**Comment by thymikee** [comment]
I think we should be fine with such change. Wonder if setting `ulimit` like this is necessary or valid? I remember setting it to even higher value sometimes anyway. This script will also not run when building from Xcode, so users may still encounter issues with too many file descriptors open

**Comment by Esemesek** [comment]
https://github.com/facebook/react-native/issues/5668
I think `ulimit` might still be necessary for some commands to run. The issue itself is quite old, but I think `/bin/bash` was there because this script was more complex back in a day (https://github.com/facebook/react-native/pull/11184/files). I'm going to create a PR to change this thing to `sh`.

**Comment by thymikee** [comment]
Closed via #1097
