### ISSUE TITLE
npx react-native init AwesomeProject --version 0.57.3 doesnt work on ubuntu with nvm

### ISSUE THREAD

**Issue by anderskitson** [react-native-community/cli#1200]
I have run the following 
`npx react-native init AwesomeProject --version 0.57.3`

and I get the following output
```
✔ Downloading template
✖ Copying template
error Error: Couldn't find the "/tmp/rncli-init-template-nSyXnK/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template
```
Without the version number it runs fine. I have tried just 0.57, 0.58, and 0.59 with the same result.
I never installed react native cli, just used npx. I am using nvm as my node version manager, and I am running node v12.18.0

Not sure how to solve this.

Thanks

**Comment by liamjones** [comment]
`npx` will be pulling the latest version of the CLI, that's only compatible with RN `^0.65`: https://github.com/react-native-community/cli#compatibility

You could try an `npx react-native@^1.0.0` but that's only compatible with `^0.59`so won't help with 0.57 or 0.58.

If you're starting a new project I wouldn't recommend using a version of RN that's over two years old but I'm guessing you have a good reason for needing the old one rather than a current one.

**Comment by liamjones** [comment]
@likern It's working fine here:

![Screenshot 2021-11-01 at 13 56 35](https://user-images.githubusercontent.com/521341/139683127-24682518-feba-406b-8dbc-ee67d8598822.png)

Maybe take a look in the temp directory mentioned in your screenshot (if it still exists) and see if there's anything in there which might highlight why it's not working on your machine?

Maybe something to do with node version? My test which just worked was on 17.0.1 if that helps.
