### ISSUE TITLE
 ^SyntaxError: Unexpected token {    at createScript (vm.js:80:10) 

### ISSUE THREAD

**Issue by adkaushik** [react-native-community/cli#1408]
## Ask your Question

Gradle sync is failing when android studio is opened. But `npx react-native run-android` command successfully builds and runs the app. 
Here is the full error: 
```
/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:48  } catch {}          ^SyntaxError: Unexpected token {    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (/home/kaushik/work/inflolabs/storefronts/test/entertainment-app/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:28:21)
```
The error points to a catch block with no argument. Is this related to node verion ?

I am using node v12.18.4.
React native version 0.64.0

**Comment by swaroopaillinda** [comment]
@adkaushik have you fixed this issues

My node is : 14.15.4
RN : ^0.64.1

**Comment by adkaushik** [comment]
Sounds dumb, but I reinstalled Android studio and the issue's fixed

**Comment by swaroopaillinda** [comment]
ok but i am getting error in iOS that too in when releasing build @adkaushik

**Comment by protyze** [comment]
I had a similar issue. It turned out to be a problem with the used node version during the build… although I had node v14 installed, I also had nvm configured to use an older version… during the build process the nvm version was used, not the one installed.

I had to manually uninstall the old version of nvm (nvm uninstall <version>) and install a newer one (nvm install <version>) - just selecting a different version with "nvm use <version>" didn't work. But afterwards, the build worked again. This error didn't appear on older RN versions (have 0.66.2 right now) – I think they abandoned support for older node versions at some point. Maybe that saves someone some time.
