### ISSUE TITLE
Add a command to enable / disable Hermes for an app

### ISSUE THREAD

**Issue by kraenhansen** [react-native-community/cli#1472]
## Describe the Feature

As a library maintainer I have a test app that I would like to run on CI with and without Hermes enabled.

I propose adding a new command (suggested name could be "set-hermes"). Running this command from an app's directory would patch the `ios/Podfile` and `android/app/build.gradle` files to enable / disable hermes respectively.

To enable, run:

```
npx react-native set-hermes true
```

To disable, run this command:

```
npx react-native set-hermes false
```

## Possible Implementations

We should implement this as a directory next to the [profileHermes](https://github.com/react-native-community/cli/tree/master/packages/cli-hermes/src/profileHermes) command. This could use regular expressions to simply search and replace the respective configuration parameters.

I'd be happy to provide a PR for this.

## Related Issues

A related issue might be: [Init: Custom replacements in template / allow Hermes flag](https://github.com/react-native-community/cli/issues/1470) but this will only solve the issue for newly initialized apps.

**Comment by kraenhansen** [comment]
Scrap that. I just realised I can simply use an environment variable and read that from the respective build scripts.

**Comment by siddarthkay** [comment]
I would be interested if such a thing existed now in the react-native cli

Since its not trivial anymore to have `hermes` disabled for debug android builds and enabled for the rest.

After we upgraded to `react-native` to `0.72.x` we found that `react-native` relies on this key `hermesEnabled` in `gradle.properties` and its hard/impossible to make this property dynamic. 

For our project its better for us to keep `hermes` disabled because of : https://github.com/status-im/status-mobile/issues/18493 but we would still like `hermes` to be enabled for release builds.

I currently have to do gymnastic like this : https://github.com/status-im/status-mobile/pull/18675 to disable `hermes` for debug builds.

Curious to know if there are easier solutions available OR if it makes sense to have this feature in react-native cli

Thank you.

**Comment by kraenhansen** [comment]
@siddarthkay have you experimented with setting 
 the Gradle setting via an environment variable? https://docs.gradle.org/current/userguide/project_properties.html I haven't tried this recently, but I do remember it being possible at some point.

**Comment by siddarthkay** [comment]
Hey @kraenhansen : Thanks for this insight, no I did not try that.. I'll take a look.

**Comment by siddarthkay** [comment]
Thanks! @kraenhansen : `export ORG_GRADLE_PROJECT_hermesEnabled := false` works for me!
