### ISSUE TITLE
cli@7.0.2 fail to start - Cannot read property 'reportEvent' of undefined

### ISSUE THREAD

**Issue by Nodonisko** [react-native-community/cli#1564]
## Environment
```
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 168.50 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /var/folders/j4/nw3_c4nd029_zvtg_cy0k1d80000gn/T/yarn--1645213250030-0.5190764815852629/node
    Yarn: 1.22.15 - /var/folders/j4/nw3_c4nd029_zvtg_cy0k1d80000gn/T/yarn--1645213250030-0.5190764815852629/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.2 => 7.0.2
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0-rc.1 => 0.68.0-rc.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

Hi, I tried to init new project `npx react-native init RN068RC1 --version 0.68.0-rc.1` but when I run `yarn start`, it will throw this error:

```
error Cannot read property 'reportEvent' of undefined.
TypeError: Cannot read property 'reportEvent' of undefined
    at Object.runServer [as func] (/Users/danielsuchy/javascript/RN068RC1/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:131:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.handleAction (/Users/danielsuchy/javascript/RN068RC1/node_modules/@react-native-community/cli/build/index.js:192:9)
```

I tried this on my second computer with same result.

I figured out this hotfix for `package.json`:
```json
  "resolutions": {
    "@react-native-community/cli": "^6.0.0",
    "@react-native-community/cli-platform-android": "^6.0.0",
    "@react-native-community/cli-platform-ios": "^6.0.0"
  }
```

## Reproducible Demo

```
npx react-native init RN068RC1 --version 0.68.0-rc.1
```

Then try to run packager `yarn start`.

**Comment by NickGerleman** [comment]
There was an issue, where cli@7.0.2 is pulling in an incorrect version of cli-server-api. @thymikee is looking to fix soon.

**Comment by Nodonisko** [comment]
@NickGerleman It looks it already fixed in `master` by #1560

**Comment by NickGerleman** [comment]
It's a little more complicated unfortunately. Originally, the new `cli-server-api` was published to npm as a patch release of 6.0.0, which broke folks before 0.68. That was fixed quickly in npm, but not yet GitHub, and a 7.0.0 version was created. But `cli-plugin-metro` still points to 6.0.0.

Talking offline to @thymikee, I think we both liked the idea of automating repo versioning/publish, to add an extra layer of defense against this in the future.

**Comment by NickGerleman** [comment]
To get the code, in #1560, you will need the above resolution for now. This should be fixed shortly, when a new package is published to npm, with the updated `cli-server-api`.

**Comment by Nodonisko** [comment]
@NickGerleman Thanks for exhausting explanation, I am always curios about how these things happen.

**Comment by thymikee** [comment]
Yup, @NickGerleman got this pretty much right :D What I can add from myself is I figured a manual "quick fix" should be good enough for this "simple" change (because there are only 2 packages and I'd need to generate artificial changes in the packages for Lerna change engine to kick in and I had many issues with Lerna detect changes and publish in the past). 

This, in retrospect obviously, wasn't a good idea, as I forgot to build the packages before publishing (lerna does that) and needed to publish yet another version for 6.x. What's more, this caused `cli` to yet again depend on a 6.x version of `cli-server-api`, which was just reverted to not include the breaking change, and I didn't notice it, huh 😅. All of that on a Friday evening. _enter what a week captain meme_ . 

So now I updated all the necessary packages to 7.0.3 through Lerna, and it should be all good. Trust your tools folks.
