### ISSUE TITLE
gradlew bundleRelease fails with error: React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration

### ISSUE THREAD

**Issue by dineshspp** [react-native-community/cli#1625]
## Environment

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 5.71 GB / 15.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
  npmPackages:
    @react-native-community/cli: 6.0.0 => 6.0.0
    react: 17.0.2 => 17.0.2
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description
I am unable to build react-native application created with expo init. I get following error when running: gradlew bundleRelease. I have given the build logs below:

PS E:\Apps\TestApp\android> .\gradlew bundleRelease        

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Apps\TestApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 206

* What went wrong:
A problem occurred evaluating script.
> React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
  [root:E:\Apps\TestApp, reactNativePath:E:\Apps\TestApp\node_modules\react-native, dependencies:[expo:[root:E:\Apps\TestApp\node_modules\expo, name:expo, platforms:[ios:[sourceDir:E:\Apps\TestApp\node_modules\expo\ios, folder:E:\Apps\TestApp\node_modules\expo, pbxprojPath:E:\Apps\TestApp\node_modules\expo\ios\Expo.xcodeproj\project.pbxproj, podfile:null, podspecPath:E:\Apps\TestApp\node_modules\expo\ios\Expo.podspec, projectPath:E:\Apps\TestApp\node_modules\expo\ios\Expo.xcodeproj, projectName:Expo.xcodeproj, libraryFolder:Libraries, sharedLibraries:[], plist:[], scriptPhases:[]], android:[sourceDir:E:\Apps\TestApp\node_modules\expo\android, folder:E:\Apps\TestApp\node_modules\expo, packageImportPath:import expo.modules.ExpoModulesPackage;, packageInstance:new ExpoModulesPackage()]], assets:[], hooks:[:], params:[]]], commands:[[name:log-ios, description:starts iOS device syslog tail], [name:run-ios, description:builds your app and starts it on iOS simulator, examples:[[desc:Run on a different simulator, e.g. iPhone 5, cmd:react-native run-ios --simulator "iPhone 5"], [desc:Pass a non-standard location of iOS directory, cmd:react-native run-ios --project-path "./app/ios"], [desc:Run on a connected device, e.g. Max's iPhone, cmd:react-native run-ios --device "Max's iPhone"], [desc:Run on the AppleTV simulator, cmd:react-native run-ios --simulator "Apple TV"  --scheme "helloworld-tvOS"]], options:[[name:--simulator [string], description:Explicitly set simulator to use. Optionally include iOS version betweenparenthesis at the end to match an exact version: "iPhone 6 (10.0)", default:iPhone 11], [name:--configuration [string], description:Explicitly set the scheme configuration to use, default:Debug], [name:--scheme [string], description:Explicitly set Xcode scheme to use], [name:--project-path [string], description:Path relative to project root where the Xcode project (.xcodeproj) lives., default:ios], [name:--device [string], description:Explicitly set device to use by name.  The value is not required if you have a single device connected.], [name:--udid [string], description:Explicitly set device to use by udid], [name:--no-packager, description:Do not launch packager while building], [name:--verbose, description:Do not use xcpretty even if installed], [name:--port [number], default:8081], [name:--terminal [string], description:Launches the Metro Bundler in a new window using the specified terminal path.]]], [name:log-android, description:starts logkitty], [name:run-android, description:builds your app and starts it on a connected Android emulator or device, options:[[name:--root [string], description:Override the root directory for the android build (which contains the android directory), default:], [name:--variant [string], description:Specify your app's build variant, default:debug], [name:--appFolder [string], description:Specify a different application folder name for the android source. If not, we assume is "app", default:app], [name:--appId [string], description:Specify an applicationId to launch after build., default:], [name:--appIdSuffix [string], description:Specify an applicationIdSuffix to launch after build., default:], [name:--main-activity [string], description:Name of the activity to start, default:MainActivity], [name:--deviceId [string], description:builds your app and starts it on a specific device/simulator with the given device id (listed by running "adb devices" on the command line).], [name:--no-packager, description:Do not launch packager while building], [name:--port [number], default:8081], [name:--terminal [string], 
description:Launches the Metro Bundler in a new window using the specified terminal path.], [name:--tasks [list], description:Run custom Gradle tasks. By default it's "installDebug"], [name:--no-jetifier, description:Do not run "jetifier" ΓÇô the AndroidX transition tool. By default it runs before Gradle to ease working with libraries that don't support AndroidX yet. See more at: https://www.npmjs.com/package/jetifier., default:false]]]], assets:[], platforms:[ios:[:], android:[:]], haste:[providesModuleNodeModules:[react-native], platforms:[ios, android]], project:[ios:null, android:null]]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

## Reproducible Demo

1. Create an blank react native application with expo command. For ex: expo init TestApp
2. Run: Yarn install
3. Create keystore file using JDK keytool
4. Place the keystore file under <project-dir>\android\app
5. Create the gradle files in <project-dir>\android
6. Run command: .\gradlew bundleRelease

The build error occurs. 

Please contact me for any additional information.

**Comment by Cnilton** [comment]
Can also reproduce this issue using Bitrise, but cannot reproduce it locally.

# Environment

Windows 11 // works
Xcode 13.2.x on macOS 12.4 (Monterey) // Bitrise doesn't work
react: 18.1.0
react-native: 0.70.2 => 0.70.2

# Description

Running .\gradlew dependencies: 

Welcome to Gradle 7.4.1!
Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains
For more details see https://docs.gradle.org/7.4.1/release-notes.html
Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.
* Where:
Script '/Users/vagrant/git/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 456
* What went wrong:
A problem occurred evaluating script.
> React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
  [root:/Users/vagrant/git, reactNativePath:/Users/vagrant/git/node_modules/react-native, dependencies:[react-native-vector-icons:[root:/Users/vagrant/git/node_modules/react-native-vector-icons, name:react-native-vector-icons, platforms:[ios:null, android:[sourceDir:/Users/vagrant/git/node_modules/react-native-vector-icons/android, packageImportPath:import com.oblador.vectoricons.VectorIconsPackage;, packageInstance:new VectorIconsPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-vector-icons/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-vector-icons/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @invertase/react-native-apple-authentication:[root:/Users/vagrant/git/node_modules/@invertase/react-native-apple-authentication, name:@invertase/react-native-apple-authentication, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@invertase/react-native-apple-authentication/RNAppleAuthentication.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@invertase/react-native-apple-authentication/android, packageImportPath:import com.RNAppleAuthentication.AppleAuthenticationAndroidPackage;, packageInstance:new AppleAuthenticationAndroidPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@invertase/react-native-apple-authentication/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@invertase/react-native-apple-authentication/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-async-storage/async-storage:[root:/Users/vagrant/git/node_modules/@react-native-async-storage/async-storage, name:@react-native-async-storage/async-storage, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-async-storage/async-storage/RNCAsyncStorage.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-async-storage/async-storage/android, packageImportPath:import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;, packageInstance:new AsyncStoragePackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-async-storage/async-storage/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-async-storage/async-storage/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-community/checkbox:[root:/Users/vagrant/git/node_modules/@react-native-community/checkbox, name:@react-native-community/checkbox, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-community/checkbox/RNCCheckbox.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-community/checkbox/android, packageImportPath:import com.reactnativecommunity.checkbox.ReactCheckBoxPackage;, packageInstance:new ReactCheckBoxPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-community/checkbox/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-community/checkbox/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-community/slider:[root:/Users/vagrant/git/node_modules/@react-native-community/slider, name:@react-native-community/slider, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-community/slider/react-native-slider.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-community/slider/android, packageImportPath:import com.reactnativecommunity.slider.ReactSliderPackage;, packageInstance:new ReactSliderPackage(), buildTypes:[], libraryName:ReactSlider, componentDescriptors:[RNCSliderComponentDescriptor], androidMkPath:/Users/vagrant/git/node_modules/@react-native-community/slider/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-community/slider/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-firebase/app:[root:/Users/vagrant/git/node_modules/@react-native-firebase/app, name:@react-native-firebase/app, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-firebase/app/RNFBApp.podspec, configurations:[], scriptPhases:[[name:[RNFB] Core Configuration, path:./ios_config.sh, execution_position:after_compile]]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-firebase/app/android, packageImportPath:import io.invertase.firebase.app.ReactNativeFirebaseAppPackage;, packageInstance:new ReactNativeFirebaseAppPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-firebase/app/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-firebase/app/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-firebase/database:[root:/Users/vagrant/git/node_modules/@react-native-firebase/database, name:@react-native-firebase/database, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-firebase/database/RNFBDatabase.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-firebase/database/android, packageImportPath:import io.invertase.firebase.database.ReactNativeFirebaseDatabasePackage;, packageInstance:new ReactNativeFirebaseDatabasePackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-firebase/database/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-firebase/database/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-firebase/messaging:[root:/Users/vagrant/git/node_modules/@react-native-firebase/messaging, name:@react-native-firebase/messaging, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-firebase/messaging/RNFBMessaging.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-firebase/messaging/android, packageImportPath:import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingPackage;, packageInstance:new ReactNativeFirebaseMessagingPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-firebase/messaging/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-firebase/messaging/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-firebase/remote-config:[root:/Users/vagrant/git/node_modules/@react-native-firebase/remote-config, name:@react-native-firebase/remote-config, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-firebase/remote-config/RNFBRemoteConfig.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-firebase/remote-config/android, packageImportPath:import io.invertase.firebase.config.ReactNativeFirebaseConfigPackage;, packageInstance:new ReactNativeFirebaseConfigPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-firebase/remote-config/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-firebase/remote-config/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-google-signin/google-signin:[root:/Users/vagrant/git/node_modules/@react-native-google-signin/google-signin, name:@react-native-google-signin/google-signin, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-google-signin/google-signin/RNGoogleSignin.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-google-signin/google-signin/android, packageImportPath:import com.reactnativegooglesignin.RNGoogleSigninPackage;, packageInstance:new RNGoogleSigninPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-google-signin/google-signin/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-google-signin/google-signin/android/build/generated/source/codegen/jni/CMakeLists.txt]]], @react-native-masked-view/masked-view:[root:/Users/vagrant/git/node_modules/@react-native-masked-view/masked-view, name:@react-native-masked-view/masked-view, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/@react-native-masked-view/masked-view/RNCMaskedView.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/@react-native-masked-view/masked-view/android, packageImportPath:import org.reactnative.maskedview.RNCMaskedViewPackage;, packageInstance:new RNCMaskedViewPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/@react-native-masked-view/masked-view/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/@react-native-masked-view/masked-view/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-device-info:[root:/Users/vagrant/git/node_modules/react-native-device-info, name:react-native-device-info, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-device-info/RNDeviceInfo.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-device-info/android, packageImportPath:import com.learnium.RNDeviceInfo.RNDeviceInfo;, packageInstance:new RNDeviceInfo(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-device-info/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-device-info/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-fast-image:[root:/Users/vagrant/git/node_modules/react-native-fast-image, name:react-native-fast-image, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-fast-image/RNFastImage.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-fast-image/android, packageImportPath:import com.dylanvann.fastimage.FastImageViewPackage;, packageInstance:new FastImageViewPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-fast-image/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-fast-image/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-gesture-handler:[root:/Users/vagrant/git/node_modules/react-native-gesture-handler, name:react-native-gesture-handler, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-gesture-handler/RNGestureHandler.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-gesture-handler/android, packageImportPath:import com.swmansion.gesturehandler.RNGestureHandlerPackage;, packageInstance:new RNGestureHandlerPackage(), buildTypes:[], libraryName:rngesturehandler_codegen, componentDescriptors:[RNGestureHandlerButtonComponentDescriptor, RNGestureHandlerRootViewComponentDescriptor], androidMkPath:/Users/vagrant/git/node_modules/react-native-gesture-handler/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-gesture-handler/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-image-crop-picker:[root:/Users/vagrant/git/node_modules/react-native-image-crop-picker, name:react-native-image-crop-picker, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-image-crop-picker/RNImageCropPicker.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-image-crop-picker/android, packageImportPath:import com.reactnative.ivpusic.imagepicker.PickerPackage;, packageInstance:new PickerPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-image-crop-picker/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-image-crop-picker/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-pager-view:[root:/Users/vagrant/git/node_modules/react-native-pager-view, name:react-native-pager-view, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-pager-view/react-native-pager-view.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-pager-view/android, packageImportPath:import com.reactnativepagerview.PagerViewPackage;, packageInstance:new PagerViewPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-pager-view/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-pager-view/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-reanimated:[root:/Users/vagrant/git/node_modules/react-native-reanimated, name:react-native-reanimated, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-reanimated/RNReanimated.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-reanimated/android, packageImportPath:import com.swmansion.reanimated.ReanimatedPackage;, packageInstance:new ReanimatedPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-reanimated/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-reanimated/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-safe-area-context:[root:/Users/vagrant/git/node_modules/react-native-safe-area-context, name:react-native-safe-area-context, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-safe-area-context/react-native-safe-area-context.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-safe-area-context/android, packageImportPath:import com.th3rdwave.safeareacontext.SafeAreaContextPackage;, packageInstance:new SafeAreaContextPackage(), buildTypes:[], libraryName:safeareacontext, componentDescriptors:[RNCSafeAreaProviderComponentDescriptor, RNCSafeAreaViewComponentDescriptor], androidMkPath:/Users/vagrant/git/node_modules/react-native-safe-area-context/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-safe-area-context/android/src/main/jni/CMakeLists.txt]]], react-native-screens:[root:/Users/vagrant/git/node_modules/react-native-screens, name:react-native-screens, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-screens/RNScreens.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-screens/android, packageImportPath:import com.swmansion.rnscreens.RNScreensPackage;, packageInstance:new RNScreensPackage(), buildTypes:[], libraryName:rnscreens, componentDescriptors:[RNSFullWindowOverlayComponentDescriptor, RNSScreenContainerComponentDescriptor, RNSScreenNavigationContainerComponentDescriptor, RNSScreenStackHeaderConfigComponentDescriptor, RNSScreenStackHeaderSubviewComponentDescriptor, RNSScreenStackComponentDescriptor, RNSSearchBarComponentDescriptor], androidMkPath:/Users/vagrant/git/node_modules/react-native-screens/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-screens/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-share:[root:/Users/vagrant/git/node_modules/react-native-share, name:react-native-share, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-share/RNShare.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-share/android, packageImportPath:import cl.json.RNSharePackage;, packageInstance:new RNSharePackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-share/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-share/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-svg:[root:/Users/vagrant/git/node_modules/react-native-svg, name:react-native-svg, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-svg/RNSVG.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-svg/android, packageImportPath:import com.horcrux.svg.SvgPackage;, packageInstance:new SvgPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-svg/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-svg/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-version-check:[root:/Users/vagrant/git/node_modules/react-native-version-check, name:react-native-version-check, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-version-check/react-native-version-check.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-version-check/android, packageImportPath:import io.xogus.reactnative.versioncheck.RNVersionCheckPackage;, packageInstance:new RNVersionCheckPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-version-check/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-version-check/android/build/generated/source/codegen/jni/CMakeLists.txt]]], react-native-video:[root:/Users/vagrant/git/node_modules/react-native-video, name:react-native-video, platforms:[ios:[podspecPath:/Users/vagrant/git/node_modules/react-native-video/react-native-video.podspec, configurations:[], scriptPhases:[]], android:[sourceDir:/Users/vagrant/git/node_modules/react-native-video/android, packageImportPath:import com.brentvatne.react.ReactVideoPackage;, packageInstance:new ReactVideoPackage(), buildTypes:[], componentDescriptors:[], androidMkPath:/Users/vagrant/git/node_modules/react-native-video/android/build/generated/source/codegen/jni/Android.mk, cmakeListsPath:/Users/vagrant/git/node_modules/react-native-video/android/build/generated/source/codegen/jni/CMakeLists.txt]]]], commands:[[name:log-ios, description:starts iOS device syslog tail], [name:run-ios, description:builds your app and starts it on iOS simulator, examples:[[desc:Run on a different simulator, e.g. iPhone SE (2nd generation), cmd:react-native run-ios --simulator "iPhone SE (2nd generation)"], [desc:Run on a connected device, e.g. Max's iPhone, cmd:react-native run-ios --device "Max's iPhone"], [desc:Run on the AppleTV simulator, cmd:react-native run-ios --simulator "Apple TV"  --scheme "helloworld-tvOS"]], options:[[name:--simulator <string>, description:Explicitly set simulator to use. Optionally include iOS version between parenthesis at the end to match an exact version: "iPhone 6 (10.0)", default:iPhone 13], [name:--configuration <string>, description:Explicitly set the scheme configuration to use, default:Debug], [name:--scheme <string>, description:Explicitly set Xcode scheme to use], [name:--device [string], description:Explicitly set device to use by name.  The value is not required if you have a single device connected.], [name:--udid <string>, description:Explicitly set device to use by udid], [name:--no-packager, description:Do not launch packager while building], [name:--verbose, description:Do not use xcbeautify or xcpretty even if installed], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.]]], [name:log-android, description:starts logkitty], [name:run-android, description:builds your app and starts it on a connected Android emulator or device, options:[[name:--variant <string>, description:Specify your app's build variant, default:debug], [name:--appId <string>, description:Specify an applicationId to launch after build. If not specified, `package` from AndroidManifest.xml will be used., default:], [name:--appIdSuffix <string>, description:Specify an applicationIdSuffix to launch after build., default:], [name:--main-activity <string>, description:Name of the activity to start, default:MainActivity], [name:--deviceId <string>, description:builds your app and starts it on a specific device/simulator with the given device id (listed by running "adb devices" on the command line).], [name:--no-packager, description:Do not launch packager while building], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.], [name:--tasks <list>, description:Run custom Gradle tasks. By default it's "installDebug"], [name:--active-arch-only, description:Build native libraries only for the current device architecture for debug builds., default:false]]]], healthChecks:[], platforms:[ios:[:], android:[:]], project:[ios:[sourceDir:/Users/vagrant/git/ios, xcodeProject:[name:horsebids.xcworkspace, isWorkspace:true]], android:null]]
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating script.

...

Caused by: java.lang.Exception: React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:
[root:/Users/vagrant/git ...

**Comment by adamTrz** [comment]
Hi @dineshspp 
I can see you have cli globally installed. Could you please try to remove it and try again?

@Cnilton your issue seems a bit different. Do you have custom project configuration? 
At the end of the log I can see:
```js
project:
  [ios:
    [sourceDir:/Users/vagrant/git/ios, xcodeProject:[name:horsebids.xcworkspace, isWorkspace:true]
  ],
  android:null
  ]
]
```
Which point to android project being null and then crashing at gradle script.

**Comment by Cnilton** [comment]
@adamTrz what do you mean by custom project configuration? react-native.config.js?

```
module.exports = {
  dependencies: {
    'react-native-vector-icons': {
      platforms: {
        ios: null,
      },
    },
  },
};
```

**Comment by adamTrz** [comment]
Yeah I meant `react-native.config.js` 

Strange, nothing fishy going there... 

Could you try to clone the CLI repo and try to debug a bit locally?

**Comment by Cnilton** [comment]
Running locally I couldn't reproduce this issue... but when running the cli through Bitrise workflow I can reproduce it. Even simply running ./gradlew dependencies will throw the same error.

**Comment by Cnilton** [comment]
@adamTrz, does it have something to do with the cli itself or is it the Bitrise environment?

**Comment by adamTrz** [comment]
> @adamTrz, does it have something to do with the cli itself or is it the Bitrise environment?

Hey @Cnilton 
Would love to say that's a Bitrise thing, but not quite sure.. ;)
Have you tried to build using different CI ?
