### ISSUE TITLE
Changes to project.pbxproj and xcworkspace after pod install

### ISSUE THREAD

**Issue by tom-sherman** [react-native-community/cli#1746]
## Environment

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.76 GB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.local/share/nvm/v16.16.0/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

The following diff is created after running `pod install` on a fresh project:

https://github.com/tom-sherman/react-native-sample-app-xcode-workspace-bug-repro/commit/cff976dd8d7de23a3465017a589a88cfe06e9d53

You can see the inverse of this diff was made in 0.70.4: https://react-native-community.github.io/upgrade-helper/?from=0.70.3&to=0.70.4

Excluding the podlock which has always been created in fresh apps, are the changes expected? What are we expected to do with these changes? Commit them? In which case, why were they removed from the sample app in the first place?

## Reproducible Demo

- `npx @react-native-community/cli init TestApp` on version 0.70.4 or 0.70.5
- Install pods
- See the change applied

Repo: https://github.com/tom-sherman/react-native-sample-app-xcode-workspace-bug-repro

**Comment by liamjones** [comment]
I believe all of these are expected.

`"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = i386;` is because your project has hermes enabled (apparently) and is set by the scripts you import into your Podfile: https://github.com/facebook/react-native/blob/7203187c808531b279ba9a9e2e73748c4254cbb6/scripts/cocoapods/utils.rb#L68

`REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";` is dynamically set because it's project specific and is set by the RN scripts you import into your Podfile: https://github.com/facebook/react-native/blob/7203187c808531b279ba9a9e2e73748c4254cbb6/scripts/cocoapods/utils.rb#L84 (for example, we use a monorepo setup so the location to the `node_modules` directory is different for us compared to you)

`ios/TestApp.xcworkspace/contents.xcworkspacedata` - this is the definition of the Xcode workspace that contains your project + the Pods generated project. You want to commit it.

**Comment by liamjones** [comment]
RN includes a `.gitignore` OOTB (https://github.com/tom-sherman/react-native-sample-app-xcode-workspace-bug-repro/blob/main/.gitignore) so standard things that shouldn't be committed (like the Cocoapods themselves) will generally already have an ignore statement: https://github.com/tom-sherman/react-native-sample-app-xcode-workspace-bug-repro/blob/main/.gitignore#L63

**Comment by tom-sherman** [comment]
@liamjones I'm aware of these. Should these things be added to the gitignore then? Or should we treat them as "generated" and commit them like we do Podfile.lock?

**Comment by liamjones** [comment]
The latter, tread them as generated changes you will want to commit

**Comment by tom-sherman** [comment]
Ah sorry I missed your first comment which explained this already, thanks for this!
