### ISSUE TITLE
Incomplete check for `@react-native/metro-config`

### ISSUE THREAD

**Issue by tido64** [react-native-community/cli#1987]
## Environment

n/a

## Description

The check for whether `@react-native/metro-config` is incomplete because `metro.config.js` is not necessarily self-contained: https://github.com/react-native-community/cli/blob/3569633e1bbda4858195feb8537d7b9969b2040e/packages/cli-plugin-metro/src/tools/loadMetroConfig.ts#L100-L104

Metro config can be split in several files (or modules) for reusability. The check fails for these scenarios. Example:  https://github.com/microsoft/rnx-kit/issues/2481

## Reproducible Demo

1. Instantiate a react-native project with 0.72
2. Refactor `metro.config.js` by moving the `@react-native/metro-config` import to a separate file
3. Bundle

**Comment by tido64** [comment]
Suggestion: Can we add a field in `@react-native/metro-config` that only gets set if it's used instead?

**Comment by kelset** [comment]
cc @huntie

**Comment by huntie** [comment]
@tido64 Yeah I've considered this. It would require adding an untyped metadata key, e.g. `'__metaBaseConfig': '@react-native/metro-config'` — which Metro's `mergeConfig` would not yet handle. Stopped short of this because we strongly recommend a single-file Metro config — but if you have clear/consistent use cases we can consider building this in.

There's also the workaround of a "suppression" comment within (e.g. at the top of) the file:

```js
// Extends '@react-native/metro-config'
```

Related:

- https://github.com/react-native-community/cli/pull/1972
- https://github.com/facebook/react-native-website/pull/3772

**Comment by huntie** [comment]
@tido64 Planned fix incoming.

**Comment by huntie** [comment]
Change has landed and should be shipped in React Native 0.72.2.

**Comment by tido64** [comment]
> Change has landed and should be shipped in React Native 0.72.2.

Thank you!
