### ISSUE TITLE
GitHub bug template assumes globally installed react-native package

### ISSUE THREAD

**Issue by liamjones** [react-native-community/cli#2031]
## Description

The environment section of the bug template says:

> Run `react-native info` in your terminal and paste its contents here.

However, having a globally installed react-native package is not recommended anymore so this, generally, shouldn't work.

I would have just raised a PR suggesting a change like:

> Run `npx react-native@latest info` in your terminal and paste its contents here.

But, due to the CLI version compatibility matrix, I wasn't sure if that was safe. It might need something like:

> Run `npm run react-native info` (or whatever equivalent command is appropriate for your package manager) in your terminal and paste its contents here.

**Comment by szymonrybczak** [comment]
Hey, thanks for creating issue! 
I think we can go safely with second option (`npx react-native@latest info`) because even if we run newer CLI version on older project with that specific command - it shouldn't have any bad effect. 
Btw. I checked and we have lot of places that we're pointing to "standalone" `react-native` command, and this should be changed 🙈
