### ISSUE TITLE
React Native Doctor is unable to detect the Android SDK

### ISSUE THREAD

**Issue by anirbanpaulcom** [react-native-community/cli#2079]
OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
  Memory: 1.68 GB / 7.10 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 16.20.2
    path: ~/.nvm/versions/node/v16.20.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.20.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v16.20.2/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10671973
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

I tried every possible way. At first, I was also facing the issue of Android Studio not being found, but after moving the directory to '/opt,' that problem was resolved. However, the issue with the Android SDK has not been resolved yet. 

![Screenshot from 2023-09-19 06-39-22](https://github.com/react-native-community/cli/assets/130109852/e5829496-0c94-4734-a742-37cad428b31a)
![Screenshot from 2023-09-19 06-39-01](https://github.com/react-native-community/cli/assets/130109852/8a098d53-bad0-4327-976b-8da0cf542ccb)
![Screenshot from 2023-09-19 06-38-34](https://github.com/react-native-community/cli/assets/130109852/a0466641-91c5-472c-af8c-3c09d9e8349d)

![Screenshot from 2023-09-19 06-38-46](https://github.com/react-native-community/cli/assets/130109852/0818ce3a-35b4-45ae-8f49-5fd335c2ca19)

![Screenshot from 2023-09-19 06-38-15](https://github.com/react-native-community/cli/assets/130109852/b9ed8
![Screenshot from 2023-09-19 06-12-56](https://github.com/react-native-community/cli/assets/130109852/eee576a1-a250-4221-a287-36843966b0ec)

![Screenshot from 2023-09-19 06-36-29](https://github.com/react-native-community/cli/assets/130109852/4836f2c3-b08c-4f96-82c6-93a92d524db7)
c46-85da-48e0-94a5-8c303bddf697)

![Screenshot from 2023-09-19 05-53-45](https://github.com/react-native-community/cli/assets/130109852/fe2405ca-e891-47fd-b3db-87b906e699a1)

**Comment by liamjones** [comment]
I've run into this issue too. For me, it was down to using a version of Java that works for RN but doesn't work for the SDK tools.

Doctor uses `envinfo` and `envinfo` uses `sdkmanager` to check what version of the Android SDK is installed: https://github.com/tabrindle/envinfo/blob/cbdd2048ea919222e4f935e82ece2a265dddd816/src/helpers/sdks.js#L6 (this may not be the exact version of `envinfo` the CLI is using right now).

We control our per-project Java SDK versions via [sdkman](https://sdkman.io/) so, for an RN 0.71 project we have this set to Java 11 (Temurin but it shouldn't matter).

If I have 11 set I can build our app but not run `sdkmanager` because it can't process the class file:

```sh
iris on  develop [$!⇣] via ☕ v17.0.8 via  v18.17.0 via 💎 v3.1.2
❯ sdk use java 11.0.19-tem

Using java version 11.0.19-tem in this shell.

iris on  develop [$!⇣] via ☕ v11.0.19 via  v18.17.0 via 💎 v3.1.2
❯ $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

It might be worth you trying to run `$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list` directly and see what output you get.

**Comment by Natetronn** [comment]
I run into this as well. If I rename latest to 11.0 (or uninstall it) and install 10.0 and rename its folder to latest (or change the path), doctor finds the SDK properly and I get all passing marks. Not sure if this is the best option for the issue, since doctor isn't necessarily what's important, but if passing is all you want then it works. Otherwise, since 11.0/latest (at time of writing) seem to work fine when building, as @liamjones said as well, I just leave it set as the latest.

**Comment by szymonrybczak** [comment]
So from CLI perspective, it is anything that we can do to fix this case?

**Comment by szymonrybczak** [comment]
So from CLI perspective, it is anything that we can do to fix this case?

**Comment by liamjones** [comment]
@szymonrybczak is there any way to get the error message from envinfo when it's called? If so, could you customise the message based on `UnsupportedClassVersionError` being present?

Otherwise, could you customise the error message if it's not found? E.g. if studio not found and JDK < 17 then add caveat message that detection may not be accurate.

You could also bump the min JDK version but that feels heavy-handed just for a tool check? E.g. RN doesn't need as high as 17 yet to compile.

**Comment by szymonrybczak** [comment]
> @szymonrybczak is there any way to get the error message from envinfo when it's called? If so, could you customise the message based on `UnsupportedClassVersionError` being present?

I think we can just go through the command's output and check if `UnsupportedClassVersionError` exists, if yes give the warning with message that we couldn't find the SDK version.

> You could also bump the min JDK version but that feels heavy-handed just for a tool check? E.g. RN doesn't need as high as 17 yet to compile.

0.73 will require, see here for more details: https://github.com/react-native-community/cli/issues/2044

**Comment by shirakaba** [comment]
For anyone running into this, I found in my case that, although I'd followed the official [environment setup](https://reactnative.dev/docs/set-up-your-environment?platform=android) docs correctly, `react-native doctor` was showing something still broken:

```sh
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ npm - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: .b34.0.0
```

I was getting the following error when attempting to sync my Gradle project:

> Gradle sync failed: Cause: com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

And thus, I had no build configurations and I couldn't build my Android app.

Then I noticed this message in my event log (if curious, [More info...](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_is_there_more_than_one_daemon_process_on_my_machine) links to the Gradle docs):

<img width="2301" alt="image" src="https://github.com/user-attachments/assets/df2cbc4d-64f3-4fae-b14a-e7d5ed0c1e10">

The message in the event log provided a link to "Select a JDK". When I clicked "Select a JDK", it showed that Android Studio had selected its own default JDK (Java version 11.0.12, corresponding to class version 55):

<img width="491" alt="image" src="https://github.com/user-attachments/assets/21881e5a-5b56-4f64-add8-fc9dd4b9c3a7">

I found I could select the one I'd configured as `$JAVA_HOME`, which was Java version 17.0.12, corrresponding to class version 61:

<img width="950" alt="image" src="https://github.com/user-attachments/assets/6d7ecb72-a1db-4c72-9a8b-d46ebac3286a">

... and now the gradle project syncs! 🚀 

My big question, as someone who doesn't touch Android all that often, is why Android Studio was so stubborn about selecting its own bundled JDK rather than heeding `$JAVA_HOME`. Maybe it only affects users who set up `$JAVA_HOME` after installing Android Studio rather than before?

Also frustrating is why Android Studio seems to have easily accessible menus by which to select the Android SDK and NDK, yet no such menu for checking the Java SDK/Runtime. If you search "Java" in `Settings...`, you can't find it.
