### ISSUE TITLE
POD ERROR

### ISSUE THREAD

**Issue by redrose4y293** [react-native-community/cli#2211]
### Discussed in https://github.com/react-native-community/cli/discussions/2210

<div type='discussions-op-text'>

<sup>Originally posted by **redrose4y293** December 17, 2023</sup>
Can Anyone help me this error i search a lot but got nothing about this error my react-native version is 0.70.0 its show this error when i install a fresh and latest version metro doesn't start automatically my OS is windows 10

![error](https://github.com/react-native-community/cli/assets/89260855/39f0d928-1f04-4fe5-b8f8-914af3f6bdbf)
</div>

**Comment by szymonrybczak** [comment]
Hey @redrose4y293, that's because you initialised project with the newest CLI on older React Native version. So for now there are two workarounds for this:
1. Remove `node_modules`, and reinstall and that should download new CLI from `react-native`'s resolution from `package.json`, if this still fails you should simply create a new project with `npx react-native@0.70 init app --version 0.70`.
2. **Not recommended**: delete `automaticPodsInstallation` field from `react-native.config.js` file.

**Comment by szymonrybczak** [comment]
@redrose4y293 any updates? :)

**Comment by szymonrybczak** [comment]
@redrose4y293 did you follow my instructions?

**Comment by szymonrybczak** [comment]
Please @redrose4y293 just run `npx react-native@latest init project` and it should work :)

**Comment by redrose4y293** [comment]
Thanks for your support. A full day I spent on react native doc and found the solution can I get your WhatsApp number for better reach and get some knowledge

**Comment by szymonrybczak** [comment]
I'm happy that it worked, if you have any other problems with CLI, or React Native just create issue in proper place :)
