### ISSUE TITLE
Incorrect version comparison link in metro command output

### ISSUE THREAD

**Issue by ErickMaeda** [react-native-community/cli#2418]
Hello!

When starting the Metro server with the react-native start --reset-cache command, it suggests updating the React Native version. However, the link provided for the upgrade comparison always compares the latest version with itself, instead of comparing the latest version with the current version being used in the project.

For example, in the output below, the current project is using version **v0.73.8**, and the latest available version is **v0.74.2**. The correct link should compare **v0.73.8** with **v0.74.2**. Instead, the link compares **v0.74.2** with itself.

```diff
react-native start --reset-cache

info Welcome to React Native v0.73
info Starting dev server on port 8081...

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


warning: the transform cache was reset.
                Welcome to Metro v0.80.4
              Fast - Scalable - Integrated


info React Native v0.74.2 is now available (your project is running on v0.73.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.2
> info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.8
< info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.2
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
info Dev server ready

i - run on iOS
a - run on Android
d - open Dev Menu
r - reload app
```

**Comment by comic222** [comment]
Same issue happened to me ,  can't find  "Caches/react-native-cli". 
`info Welcome to React Native v0.74
info Starting dev server on port 8081...

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.80.9
              Fast - Scalable - Integrated


metro-file-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: watchman::QueryExecError: query failed: synchronization failed: sync: creat(/Users/comiczhang/Documents/workspace/ReactNative/Comic_Trials/MyAwesRnProject1/.watchman-cookie-Comics-MacBook-Pro.local-923-1) failed: Permission denied: Permission denied. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
info Dev server ready

i - run on iOS
a - run on Android
d - open Dev Menu
r - reload app

info Opening app on iOS...
info A dev server is already running for this project on port 8081.`

And before run it , I checked the port 8081 if it's been used , with the command "sudo lsof -i :8081
",  nothing until this running trigged,

**Comment by szymonrybczak** [comment]
hey @comic222, your issue seems to be different and I'm not sure if I understand it correctly - if it still happens please open a new one with relevant description etc.
