### ISSUE TITLE
Android CLI plugin regex lookup includes comments, fails the build

### ISSUE THREAD

**Issue by tjzel** [react-native-community/cli#2497]
Recently I was confused when my build started to use wrong namespace, therefore failing to compile.  When I changed the namespace I left a comment with the old namespace in `build.gradle`. Turns out the `namespace` is extracted from `build.gradle` (among other properties) with a regex. In my opinion this is short-sighted, since it causes the following flow to fail the build process:

```gradle
// this is a namespace "fix"

// more build.gradle code

namespace "com.library"
```

In such scenario the plugin registers the namespace as `fix`.

https://github.com/react-native-community/cli/blob/e3bc0ddcba67cdd6b7fd6c04b5a8a87931e9d086/packages/cli-platform-android/src/config/getAndroidProject.ts#L94-L102

**Comment by szymonrybczak** [comment]
Hey @tjzel! It's an edge case and in my opinion there's no good way of solving this issue because composing config is done before running build.

We'd need to fallback to other namespace in this scenario when Android build fails, but IMO this adds more *a lot more* complexity and unnecessary logic. Same issue probably applies to other regexes that we have to get values to compose config.

**Comment by thymikee** [comment]
@tjzel it's fast and already there working fine for most cases. Last time I checked there was no official nor usable Gradle to JS parser. If there's something worth integrating out there that's lightweight and fast, I'm happy to review a PR with it.
