### ISSUE TITLE
npm init react-native support

### ISSUE THREAD

**Issue by wtrocki** [react-native-community/cli#343]
`npm init react-native` finishes with error:
`command not found: create-react-native`

Current documentation is yarn based, while the general node community and react is basing on `npm init` command to create apps. 
For example `npm init react-app my-app`. 
Happy to contribute that change back to cli.

**Comment by thymikee** [comment]
I don't think I understand what's the issue here, can you elaborate? 

`create-react-native` is not a package React Native community maintains. There was `create-react-native-app` but it was deprecated.

The preferred way to init new RN projects currently is through global CLI and the instructions are well defined: https://github.com/react-native-community/cli/tree/master/packages/global-cli.

**Comment by wtrocki** [comment]
> There was create-react-native-app but it was deprecated.

I missed that. Thanks for the explanation.
