### ISSUE TITLE
Using template arg with `file:`, `.tgz`, or `https` fails

### ISSUE THREAD

**Issue by sartaj** [react-native-community/cli#385]
## Environment

```
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```
## Description

Using any non `react-native-template-*` path fails with the same error. This could be a regression, as the CLI code has tests for these different kinds of paths.

### `.tgz`

```
react-native init AppName --template=https://registry.npmjs.org/react-native-template-typescript/-/react-native-template-typescript-5.0.1.tgz
```
```
Error: ENOENT: no such file or directory, lstat 'SCRUBBED/AppName/node_modules/react-native-template-typescript-5.0.1.tgz'
```

### Local file

_this is a clone of the typescript template_

```
react-native init AppName --template=file:~/Desktop/fs/cloned_template
```

```
Error: Command failed: yarn add react-native-template-file:~/Desktop/fs/cloned_template
```

**Comment by thymikee** [comment]
We don't have incentive to work on legacy init at this point (by legacy I mean the one you access through global `react-native` binary exposed by global `react-native-cli` package). Since React Native 0.60 you will be able to do it with new `init` command that will be accessible through local `react-native` binary or directly from `@react-native-community/cli` package. It's already available in our alphas on `next` tag. Feel free to try:

```
npx @react-native-community/cli@next init
```
