### ISSUE TITLE
warn The following packages use deprecated "rnpm" config that will stop working from next release:   - react-native-nearby-api: https://github.com/badfeatures/react-native-nearby-api#readme

### ISSUE THREAD

**Issue by cgrio** [react-native-community/cli#834]
## Ask your Question
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-nearby-api: https://github.com/badfeatures/react-native-nearby-api#readme
After install in react I receive this inforamation.

Using react-native 0.61

**Comment by thymikee** [comment]
Please contact `react-native-nearby-api` maintainers using the link provided, to upgrade their setup to autolinking. Or even better, send a PR yourself! Removing these lines should do just fine: https://github.com/badfeatures/react-native-nearby-api/blob/master/package.json#L42-L46 since their setup is pretty common (I assume this library is automatically linked by the CLI, the warning is just for awareness).
